# Generated by Django 4.2.4 on 2023-09-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
