# Generated by Django 4.2.4 on 2023-09-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(default='Bamenda', max_length=100),
        ),
    ]
